version: "3.8"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloak
    command: start-dev
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-pgsql
      - KC_DB_URL_DATABASE=${POSTGRES_KEYCLOAK_DB}
      - KC_DB_USERNAME=${POSTGRES_KEYCLOAK_USER}
      - KC_DB_PASSWORD=${POSTGRES_KEYCLOAK_PASSWORD}
      - KC_DB_SCHEMA=public
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_THEME_FOLDER_DIR=/opt/keycloak/themes/mytheme
      - DEBUG='true'
      - DEBUG_PORT='*:8787'
      - KC_FEATURES=preview
    ports:
      - 8080:8080
    depends_on:
      keycloak-pgsql:
        condition: service_healthy
    volumes:
      - ./keycloak/mytheme:/opt/keycloak/themes/mytheme
      - ./keycloak/event-listener-spi/target/event-listener-spi.jar:/opt/keycloak/providers/event-listener-spi.jar
      # - ./keycloak/event-listener-spi/dasniko.keycloak-event-listener.jar:/opt/keycloak/providers/keycloak-event-listener.jar
      # - ./keycloak/event-listener-sysout/target/event-listener-sysout.jar:/opt/keycloak/providers/event-listener-sysout.jar

  keycloak-pgsql:
    container_name: keycloak-pgsql
    image: postgres:16.2
    environment:
      - POSTGRES_USER=${POSTGRES_KEYCLOAK_USER}
      - POSTGRES_PASSWORD=${POSTGRES_KEYCLOAK_PASSWORD}
      - POSTGRES_DB=${POSTGRES_KEYCLOAK_DB}
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d ${POSTGRES_KEYCLOAK_DB} -U ${POSTGRES_KEYCLOAK_USER}",
        ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - keycloakpgsql-vol:/var/lib/postgresql/data
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  keycloakpgsql-vol:
