
version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start-dev
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-pgsql
      - KC_DB_URL_DATABASE=${POSTGRES_KEYCLOAK_DB}
      - KC_DB_USERNAME=${POSTGRES_KEYCLOAK_USER}
      - KC_DB_PASSWORD=${POSTGRES_KEYCLOAK_PASSWORD}
      - KC_DB_SCHEMA=public
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      keycloak-pgsql:
        condition: service_healthy
  keycloak-pgsql:
    container_name: keycloak-pgsql
    image: postgres:16.2
    environment:
      - POSTGRES_USER=${POSTGRES_KEYCLOAK_USER}
      - POSTGRES_PASSWORD=${POSTGRES_KEYCLOAK_PASSWORD}
      - POSTGRES_DB=${POSTGRES_KEYCLOAK_DB}
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_KEYCLOAK_DB} -U ${POSTGRES_KEYCLOAK_USER}"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - keycloakpgsql-vol:/var/lib/postgresql/data
volumes:
    keycloakpgsql-vol: